name: Terraform Azure workflow
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Print the value
        run: echo "hello world"
      - name: Print end
        run: echo "end"
